/** Declaration file generated by dts-gen */

declare namespace Stomp {
    export class Frame {
        constructor(command: any, headers: any, body: any);

        toString(): any;

        static marshall(command: any, headers: any, body: any): any;

        static sizeOfUTF8(s: any): any;

        static unmarshall(datas: any): any;

    }

    export function clearInterval(id: any): any;

    export function client(url: any, protocols: any): any;

    export function over(ws: any): any;

    // export function overTCP(host: any, port: any): any;

    // export function overWS(url: any): any;

    export function setInterval(interval: any, f: any): any;

    export namespace VERSIONS {
        const V1_0: string;

        const V1_1: string;

        const V1_2: string;

        function supportedVersions(): any;

    }
}
